"Filed out from Dolphin Smalltalk 7"!

MatrixTest subclass: #FloatMatrixTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
FloatMatrixTest guid: (GUID fromString: '{1ebb4965-0174-4958-8ade-be3e9cf3f6a0}')!
FloatMatrixTest comment: ''!
!FloatMatrixTest categoriesForClass!Unclassified! !
!FloatMatrixTest methodsFor!

matrixClassToTest
	^FloatMatrix! !
!FloatMatrixTest categoriesFor: #matrixClassToTest!accessing!public! !

