"Filed out from Dolphin Smalltalk 7"!

FlipperInspector subclass: #FlipperInspectorW
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
FlipperInspectorW guid: (GUID fromString: '{dca0775e-ca20-4d34-b4ac-b498f72811c1}')!
FlipperInspectorW comment: ''!
!FlipperInspectorW categoriesForClass!Development! !
!FlipperInspectorW class methodsFor!

isUnicodeMode

	^true.! !
!FlipperInspectorW class categoriesFor: #isUnicodeMode!public! !

