"Filed out from Dolphin Smalltalk 7"!

TestUnicodeShell subclass: #TestNonUnicodeShell
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
TestNonUnicodeShell guid: (GUID fromString: '{2eb17404-7c0f-4ad3-bacc-1b33aac5f559}')!
TestNonUnicodeShell comment: 'self show'!
!TestNonUnicodeShell categoriesForClass!MVP-Presenters! !
!TestNonUnicodeShell class methodsFor!

isUnicodeMode

	^false! !
!TestNonUnicodeShell class categoriesFor: #isUnicodeMode!public! !

